---
title: "playground"
author: "Tiffany Hsu"
date: "2/17/2022"
output: html_document
---

```{r setup, include=FALSE, warnings = FALSE, message=FALSE}
library(tidyverse)
library(here)
library(janitor)
library(sf)
```

```{r}
covid_food <- read_csv(here("data/covid_food.csv")) %>%
  clean_names()

```


# widget 1

- Widget 1: Radio buttons to select the age range (18-24, 25-39, 40-54, 55-64, 65 and above)
- Output 1: Bar graph to visualize the change in survey responses based in the US. (ie. Enough of the kinds of food wanted, Enough Food, but not always the kinds wanted, Sometimes not enough to eat, Often not enough to eat, Did not report)

View for a certain age range (US) - bar graph
18-24, 25-39, 40-54, 55-64, 65 and above

```{r}
# step 1: only filter for only age ranges
age_range <- covid_food %>% 
  filter(
    age == "18 - 24")

for (i in 1:length(age_range$week)) {
age_range$week[[i]] <- str_replace(age_range$week[[i]], "week", "")
}

age_range$week <- sapply(age_range$week, as.numeric) 


age_range_by_week <- age_range %>% 
  group_by(week) %>% 
  summarize((sum(enough_of_the_kinds_of_food_wanted) + sum(enough_food_but_not_always_the_kinds_wanted))/ (sum(enough_of_the_kinds_of_food_wanted) + sum(enough_food_but_not_always_the_kinds_wanted) + sum(sometimes_not_enough_to_eat) + sum(often_not_enough_to_eat) + sum(did_not_report) )) %>% 
  rename(enough_of_the_kinds_of_food_wanted_ratio = '`/`(...)')

ggplot(data = age_range_by_week, aes(x = week, y = enough_of_the_kinds_of_food_wanted_ratio)) +
  geom_line(color = "darkgreen") +
  theme_minimal() +
  labs(y = "Number of People Indicating Enough Food", #label y,
       x = "Week Number") #+#and x axis
  #scale_y_continuous(labels = scales::comma)

   #   age == "25 - 39",
  #   age == "40 - 54",
  #   age == "55 - 64",
  #   age == "65 and above"
  # )
```

```{r}
# INCOME LEVELS

income_range <- covid_food %>% 
  filter(
    income == "Less than $25,000")

for (i in 1:length(income_range$week)) {
income_range$week[[i]] <- str_replace(income_range$week[[i]], "week", "")
}

income_range$week <- sapply(income_range$week, as.numeric) 


income_range_by_week <- income_range %>% 
  group_by(week) %>% 
  summarize((sum(enough_of_the_kinds_of_food_wanted) + sum(enough_food_but_not_always_the_kinds_wanted)) / (sum(enough_of_the_kinds_of_food_wanted) + sum(enough_food_but_not_always_the_kinds_wanted) + sum(sometimes_not_enough_to_eat) + sum(often_not_enough_to_eat) + sum(did_not_report) )) %>% 
  rename(enough_of_the_kinds_of_food_wanted_ratio = '`/`(...)')

ggplot(data = income_range_by_week, aes(x = week, y = enough_of_the_kinds_of_food_wanted_ratio)) +
  geom_line(color = "darkgreen") +
  theme_minimal() +
  labs(y = "Number of People Indicating Enough Food", #label y,
       x = "Week Number") 
```

```{r}
#WIDGET 3
#"Widget 3: Checkbox group allowing viewers to select level(s) of anxiety felt since last surveyed. An additional slider bar allows selection of week(s) to view. We may want to also factor food insecurity into this (ie. can also radio select which response to food insecurity the person gave relative to their anxiety level).
#Output 3: Map including every US state; each state changes in saturation with higher number of responses for that level (or combined levels, if selecting more than one) of anxiety."

us_states <- read_sf(here("data", "us_states", "cb_2018_us_state_5m.shp")) %>%
  clean_names() %>%
  rename(location = stusps) %>%
  filter(location != "VI", 
         location != "GU", 
         location != "MP", 
         location != "AS", 
         location != "PR",
         location != "HI",
         location != "AK") %>%
         #location %in% c("CA","OR","AZ","WA","NV","WY","UT","ID","CO","NM")) 
  select(location, geometry) 
  
covid_food_no_us <- covid_food %>%
  filter(location != "US")
  
plot_data <- covid_food_no_us %>%
  group_by(week, location, freq_feel_anxious) %>%
  drop_na(freq_feel_anxious) %>%
  mutate(totals = enough_of_the_kinds_of_food_wanted +
         enough_food_but_not_always_the_kinds_wanted +
         sometimes_not_enough_to_eat +
         often_not_enough_to_eat +
         did_not_report) %>%
  select(#enough_of_the_kinds_of_food_wanted, 
         #enough_food_but_not_always_the_kinds_wanted, 
         #sometimes_not_enough_to_eat, 
         #often_not_enough_to_eat, 
         #did_not_report,
         totals,
         freq_feel_anxious, 
         location, 
         week) %>%
  summarize(sum(totals)) %>%
  rename(responses = 'sum(totals)') %>%
  mutate(response_pct = responses / sum(responses) * 100) %>%
  filter(freq_feel_anxious == 'Not at all', week %in% 1:36) 

us_merged <- merge(plot_data, us_states, by = 'location')

us_merged_means <- us_merged %>%
  group_by(location, freq_feel_anxious) %>%
  mutate(mean_pct = mean(response_pct)) #%>%
  #filter(week == 'week1')
  
  

ggplot(data = us_merged_means, aes(geometry = geometry)) +
  geom_sf(aes(fill = mean_pct), color = "white", size = 0.1) +
  theme_void() +
  scale_fill_gradientn(colors = c("palegreen","green","darkgreen"))

```

```{r}
#WIDGET 4
#"Widget 4: Select box dropdown allowing viewers to choose a reason for not working since last surveyed. We may want to also factor food insecurity into this (ie. can also radio select which response to food insecurity the person gave relative to their reason for not working).
#Output 4: Line graph of people who selected that reason in the survey for the entire US over the time period of the dataset (Week 1 to Week 36)."

no_work_reason <- covid_food %>% 
  filter(
    reason_not_working == "Did not want to be employed")

us_states <- read_sf(here("data", "us_states", "cb_2018_us_state_5m.shp")) %>%
  clean_names() %>%
  rename(location = stusps) %>%
  filter(location != "VI", 
         location != "GU", 
         location != "MP", 
         location != "AS", 
         location != "PR",
         location != "HI",
         location != "AK") %>%
         #location %in% c("CA","OR","AZ","WA","NV","WY","UT","ID","CO","NM")) 
  select(location) 

us_merged <- merge(no_work_reason, us_states, by = 'location')

work_reason_survey <- no_work_reason %>% 
  mutate(sum_1 = sum(enough_of_the_kinds_of_food_wanted), 
         sum_2 = sum(enough_food_but_not_always_the_kinds_wanted), 
         sum_3 = sum(sometimes_not_enough_to_eat), 
         sum_4 = sum(often_not_enough_to_eat), 
         sum_5 = sum(did_not_report)) %>%
  select(sum_1, sum_2, sum_3, sum_4, sum_5) %>%
  head(1) %>%
  t() %>%
  as.data.frame() %>%
  rename(values = "V1")

work_reason_survey$names <- c("Enough - Wanted", "Enough - Not Always Wanted", "Sometimes Not Enough", "Often Not Enough", "Did not report")



ggplot(data=work_reason_survey, aes(x=reorder(names, values), y=values)) +
  geom_bar(fill = "darkgreen", stat = "identity") +
  coord_flip() +
  theme_minimal() +
  scale_y_continuous(labels = scales::comma) +
  labs(y = "Survey Response", #label y,
       x = "Number of People Selected")
  
```

